### ISSUE TITLE
GetSystemTimePreciseAsFileTime function in EventDataExtensions not supported on operating systems before windows 8

### ISSUE THREAD

**Issue by arturwa** [Azure/diagnostics-eventflow#142] opened 2017-10-20 11:08 UTC
GetSystemTimePreciseAsFileTime is not supported on operating systems prior Windows 8
Latest update ( Nuget Package 1.1.3)  throws exceptions on Windows 7 running NET 4.6.1, NETCore 2.0

**Comment by karolz-ms** [comment] 2017-10-20 15:54
Closed inadvertently--"thank you!" Github :-/

**Comment by karolz-ms** [comment] 2017-10-20 15:56
@arturwa Thank you for reporting this issue.

Can you try NuGet package 1.1.4 (just uploaded) to see if it fixes the problem?

**Comment by karolz-ms** [comment] 2017-11-07 17:16
I assume the problem is fixed, but let me know if the new version does not work for you

**Closed by karolz-ms** 2017-11-07 17:16 UTC
