### ISSUE TITLE
TypeLoaderException thrown when calling ServiceFabricDiagnosticPipelineFactory.CreatePipeline

### ISSUE THREAD

**Issue by barryschulz** [Azure/diagnostics-eventflow#171] opened 2018-01-18 15:30 UTC
**Steps**

1. Create new .Net461 Stateful Service 
2. Update project to use dotnet sdk (see content of csproj below)
3. Delete packages.config
4. Cleanup redundant attributes in AssemblyInfo.cs
5. Add pipeline to Main method
`using (var diagnosticsPipeline = ServiceFabricDiagnosticPipelineFactory.CreatePipeline("MyApplication-MyService-DiagnosticsPipeline"))`

**Result**

> System.TypeLoadException
>   HResult=0x80131522
>   Message=Method 'get_Properties' in type 'Microsoft.Extensions.Configuration.ConfigurationBuilder' from assembly 'Microsoft.Extensions.Configuration, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
>   Source=Microsoft.Diagnostics.EventFlow.ServiceFabric
>   StackTrace:
>    at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricDiagnosticPipelineFactory.CreatePipeline(String healthEntityName, String configurationFileName, String configurationPackageName)
> 

**Notes**
- This is similar to https://github.com/Azure/diagnostics-eventflow/issues/154. 
- I have tried the workaround mentioned here https://github.com/dotnet/standard/issues/481. 
- Problem seems to be a conflict with Microsoft.Extensions.Configuration and Microsoft.Extensions.Configuration.Abstractions (EventFlow references 1.1.1.0 + EF Core 2.0 use 2.0.0.0) 
- I tried clearing my nuget cache, the packages folder, deleted the entire source folder, restarted VS and 
restarted my machine
- I have tried .net 462 and 471
- I have tried adding bindingRedirects 
`   <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
         <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.Configuration.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
         </dependentAssembly>
         <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.Configuration" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
         </dependentAssembly>
      </assemblyBinding>`
- I have tried bindingRedirects + specifically adding the 2.0.0.0 configuration packages which resulted in the following exception.
> Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> Microsoft.Extensions.Configuration.IConfigurationBuilder.get_Properties()'.

**Example csproj**
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
	<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Inputs.EventSource" Version="1.2.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Outputs.StdOutput" Version="1.1.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.ServiceFabric" Version="1.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.ServiceFabric" Version="6.0.232" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="2.8.232" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="2.8.232" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>
</Project>`

**Comment by karolz-ms** [comment] 2018-01-18 16:55
@barryschulz many thanks for a detailed report! I can reproduce the problem. Pinging my .NET FX buddies here...

**Comment by joperezr** [comment] 2018-01-18 19:15
I'm taking a look but it seems to be that what is going on is what is described here: https://stackoverflow.com/questions/948785/typeloadexception-says-no-implementation-but-it-is-implemented

**Comment by karolz-ms** [comment] 2018-01-18 21:54
@barryschulz This is, essentially, an issue external to EventFlow. Once ASP.NET publishes a new Nuget for Ms.Ex.Configuration, we will be able to reference it from EventFlow.ServiceFabric and the issue will be fixed.

**Comment by barryschulz** [comment] 2018-01-18 23:22
Thanks for looking into this. 

I am not however seeing difference between ConfigurationBuilder and IConfigurationBuilder in 1.1.1.0. Where are seeing the problem?

![image](https://user-images.githubusercontent.com/845365/35126513-b7a40510-fc7b-11e7-93e9-5cb20fd25441.png)

![image](https://user-images.githubusercontent.com/845365/35126629-481130fa-fc7c-11e7-80f6-bd535e6beecc.png)

**Comment by joperezr** [comment] 2018-01-18 23:49
There is no difference, but if you check into the metadata of `Microsoft.Extensions.Configuration` you'll see that the typeref to `IConfigurationBuilder` doesn't contain the `Properties` property, which means that its own `Properties` is considered a new member and not an implementation of the interface. That is why a consumer of both assemblies will not consider the `Properties` member from the interface be implemented by the `ConfigurationBuilder` class. This is fixed by rebuilding the implementation assembly after updating the interface assembly version.

**Comment by tmandekic** [comment] 2018-03-10 17:23
I am not sure if this has been resolved, but it is still an issue for me.
I tried to integrate Diagnostics into my Stateless service and it causes above stated exception. I also have Web API and Web app using Diagnostics and those projects do not have an issue. It seems there is only an issue if/when Microsoft.Extensions.Configuration is explicitly included in the same project as Diagnostics.
I am using the latest nuget Microsoft.Diagnostics.EventFlow.ServiceFabric v 1.2.1
Microsoft.Extensions.Configuration nuget has been updated Feb 26 to version 2.1.0-preview1-final)

**Comment by karolz-ms** [comment] 2018-03-12 15:16
@tmandekic can you verify it is the exact same exception message? In particular, is your application trying to load Microsoft.Extensions.Configuration 1.1.1.0? If so it could be that you will need to add some binding redirects to force it to load 2.x version

The .NET Framework issue (referenced above) has not been resolved yet, so I assume the FX 1.x series is still affected

**Comment by karolz-ms** [comment] 2018-04-25 19:36
Turns out there are some breaking changes between Microsoft.Extensions.Configuration 1.1. and 2.0. I was not fully aware of this, my apologies. The proper fix is to produce netstandard2.0 version of all relevant EventFlow assemblies.

We already have [a PR for this](https://github.com/Azure/diagnostics-eventflow/pull/184). I am going to try to shepherd it to completion and publish relevant packages on Nuget in the next couple of days.

**Comment by karolz-ms** [comment] 2018-05-01 23:27
Service Fabric output package version 1.4 should have netstandard 2.0 binaries that do not exhibit this problem. @barryschulz @tmandekic please let us know if you still run into issues after upgrading the package.

**Closed by karolz-ms** 2018-05-01 23:27 UTC
