### ISSUE TITLE
Why not use extention.logging as the ingest

### ISSUE THREAD

**Issue by bklooste** [Azure/diagnostics-eventflow#89] opened 2017-05-28 00:06 UTC
Why not use extention.logging as the ingest and add providers to it , rather than 2 sets.

**Comment by karolz-ms** [comment] 2017-05-29 16:03
@bklooste Not sure I understand your point, can you elaborate?

**Comment by karolz-ms** [comment] 2017-06-02 20:30
Closing this for now as it is not entirely clear what the issue is, sorry.

**Closed by karolz-ms** 2017-06-02 20:30 UTC
