### ISSUE TITLE
Microsoft.Extensions.Logging input doesn't preserve structure

### ISSUE THREAD

**Issue by davidfowl** [Azure/diagnostics-eventflow#115] opened 2017-07-19 06:05 UTC
All of the key value pairs passed via structured logging aren't preserved. Here's an example using it with the ElasticSearch output:

![image](https://user-images.githubusercontent.com/95136/28352571-109c25f4-6c0c-11e7-9544-26cc6a31211a.png)

Compare this to the serilog elastic search log provider:

![image](https://user-images.githubusercontent.com/95136/28352848-8dd24f20-6c0d-11e7-9000-85267cffce86.png)

**Comment by karolz-ms** [comment] 2017-07-24 23:59
@davidfowl I cannot reproduce this. Can you show me the code that you use to produce these logs?

FYI it seems to work fine for calls like this

`logger.LogInformation("Hello from {friend} for {family}!", "LoggerInput", "EventFlow"); `

**Comment by karolz-ms** [comment] 2017-08-01 16:12
@davidfowl closing for now--but please feel free to reopen and share the repro, TIA

**Closed by karolz-ms** 2017-08-01 16:12 UTC
