### ISSUE TITLE
FileNotFoundException thrown during Stateful reliable service startup PipelineFactory.CreatePipeline call

### ISSUE THREAD

**Issue by SvenVanHauwe** [Azure/diagnostics-eventflow#154] opened 2017-11-30 10:01 UTC
I have added Eventflow to a stateful service recently, works on my local development service fabric instance.
After I deployed it to our azure service fabric (test) environment the service failed to activate. The event log on the node had following entries. the file eventFlowConfig.json is present in the Config.<version> directory on that node.

Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricDiagnosticPipelineFactory.CreatePipeline(System.String, System.String, System.String)
   at LayerAggregatorServicesManager.Program.Main()

**Comment by karolz-ms** [comment] 2017-11-30 17:03
This usually means that the deployment cluster does not have some dependencies that the application expects. For example, the application might be targeting a version of the .NET Framework that is not installed on cluster nodes. It just so happens that EventFlow is called early from service Main() method and triggers assembly resolution that fails, resulting in FileNotFound exception

**Comment by karolz-ms** [comment] 2017-11-30 17:05
@SvenVanHauwe when you figure out what the problem was, please let us know--it will be helpful for people who run into the same problem. We had another [issue like this one](https://github.com/Azure/diagnostics-eventflow/issues/147) and it was not fully explained

**Comment by SvenVanHauwe** [comment] 2017-12-01 07:04
I enabled logging bindings on one node, netstandard 2.0 failed to load. 

LOG: DisplayName = netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///D:/SvcFab/_App/svcFType_App2/LayerAggregatorServicePkg.Code.1.0.0/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = LayerAggregatorService.exe
Calling assembly : Microsoft.Extensions.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.

**Comment by SvenVanHauwe** [comment] 2017-12-01 07:21
I think my problem might have something to do with [https://github.com/dotnet/standard/issues/481](url) Issues with .NET Standard 2.0 with .NET Framework & NuGet.

The reliable services which fail are targeting framework 4.6.2, and use packages.config.

**Comment by karolz-ms** [comment] 2017-12-01 17:07
@SvenVanHauwe @oliverbes so is the workaround described in https://github.com/dotnet/standard/issues/481 (enable auto-generation of binding redirects and using PackageReference instead of packages.config) feasible for you? And if yes, does your application work when you apply it?

It would be great if we could reproduce the problem outside of Service Fabric. I suspect a machine with .NET Fx 4.6.2 but without .NET Core FX would do. Will try that in the next few days, but let me know if you find something interesting in the meantime.

**Comment by oliverbes** [comment] 2017-12-01 18:45
I actually gave it a try this afternoon - i.e. converting my SF Service's project file for auto-generated binding re-directs and using PackageReference instead of packages.config - but it failed. 
My SF Service is now completely broken, probably I screwed the project file somehow.

As of my understanding, only the top-level NuGet Packages would get a PackageReference setting in the project file, right? Would that be sufficient?
So in my case the list of PackageRefence settings would look like:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Core" version="1.1.8" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.EtwUtilities" version="1.1.1" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Inputs.EventSource" version="1.2.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Outputs.ElasticSearch" version="2.2.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.Outputs.StdOutput" version="1.1.0" />
    <PackageReference Include="Microsoft.Diagnostics.EventFlow.ServiceFabric" version="1.1.4" />
    <PackageReference Include="Microsoft.ServiceFabric" version="5.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" version="2.7.198" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" version="2.7.198" />
    <PackageReference Include="Newtonsoft.Json" version="10.0.3" />
    <PackageReference Include="Elasticsearch.Net" version="5.5.0" />
    <PackageReference Include="NEST" version="5.5.0" />
    <PackageReference Include="Validation" version="2.4.18" />
    <PackageReference Include="NETStandard.Library" version="2.0.1" />
  </ItemGroup>  

```
Would that list be OK? Anything missing?

**Comment by SvenVanHauwe** [comment] 2017-12-04 07:54
@karolz-ms I decided rebuild my solution from scratch, dividing the different microservices into different solutions was something on my todo list anyway.
This gives me the opportunity to use the new project templates and packagereferences. Will inform you when it's done.

**Comment by SvenVanHauwe** [comment] 2017-12-15 07:48
@karolz-ms I changed the csproj file as indicated in [dotnet/standard#481](https://github.com/dotnet/standard/issues/481), but still get the same exception.
When I build locally using visual studio 2017, the netstandard dll is copied to the bin directory.
On my build server, that dll is not included.

**Comment by SvenVanHauwe** [comment] 2017-12-15 09:56
@karolz-ms Finally got one of the services to work on an azure servicefabric cluster.
I changed the csproj file of that service to the new format. After removing some binding redirect leftovers in App.Config I was finally able to build and deploy both locally and on our build server.

**Comment by karolz-ms** [comment] 2017-12-15 17:04
@SvenVanHauwe so is the application working as expected now? If so, can you describe what the fix/workaround was?

**Comment by SvenVanHauwe** [comment] 2017-12-18 06:48
@karolz-ms  yes the application is working.
I modified the csproj files of the reliable services to use the new format, see the [blog from Nate McMaster](http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/).

Just removing package.config and using packagereferences in csproj was not enough in my case. The project build, deployed and worked on my development local cluster. 
It also build on our build server, however without netstandard dll in the output directory, which in turn gave a FileNotFound runtime exception.
My build definition contains a nuget install task to install and use nuget 4.3, and a visual studio build task  to build the solution.

**Comment by karolz-ms** [comment] 2018-01-02 16:45
OK, sorry for being dense here, but for the sake of other users, when you say 

> Just removing package.config and using packagereferences in csproj was not enough in my case. 

then do you remember what _did make it work_ when deployed to remote cluster?

**Comment by SvenVanHauwe** [comment] 2018-01-08 08:44
@karolz-ms 
I changed the project so it uses the dotnet sdk.
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <Configurations>Debug;Release;azureDev</Configurations>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup>
    <IsServiceFabricServiceProject>true</IsServiceFabricServiceProject>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
  </PropertyGroup>
  <PropertyGroup>
    <UpdateServiceFabricManifestEnabled>true</UpdateServiceFabricManifestEnabled>
    <ServicePackagePath>PackageRoot</ServicePackagePath>
    <ServicePackagePrefix>$(MSBuildProjectName)</ServicePackagePrefix>
  </PropertyGroup>
  <ItemGroup>
    <None Include="PackageRoot\Config\Settings.xml" />
    <None Include="PackageRoot\ServiceManifest.xml" />
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="2.8.232" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SeedingConfiguration.Interfaces\SeedingConfiguration.Interfaces.csproj" />
  </ItemGroup>
</Project>`

**Comment by karolz-ms** [comment] 2018-01-09 00:41
Roger! 

Since it is working, I am going to close this issue for now

**Closed by karolz-ms** 2018-01-09 00:41 UTC
