### ISSUE TITLE
Json based inputType

### ISSUE THREAD

**Issue by voltcode** [Azure/diagnostics-eventflow#288] opened 2018-11-16 15:03 UTC
EventFlow can output JSON via HTTP, but does not come with an inputType that accepts such JSON. 
It would be beneficial for building services that unify collection from other services before processing them further. For example service A uses EventFlow to output events to service B (via HTTP). Now service B accepts this JSON to push it further. This could limit the duplication of logging processing in various services, esp on-premises.

Are there any plans to implement a JSON-based inputType?

**Comment by karolz-ms** [comment] 2018-11-16 16:54
@voltcode good question I believe you are asking for an HTTP input that accepts data in JSON format.

EventFlow was conceived primarily as means to capture diagnostic data about a single service process--it is an in-process telemetry broker. What you are asking pushes it into being a telemetry broker with a network interface. This is a significant scope enhancement, that involves coming up with a story for things like network connection management and parsing/validating incoming data, potentially untrusted. We have no plans for such enhancement at the moment and, frankly, I do not think we will ever do this, given there are already mature, open-source technologies that fit this description such as Logstash or fluentD.

That said, an application-specific HTTP input can be relatively easily added to EventFlow, since the only requirement for an EventFlow input is to be `IObservable<EventData>`. If you have any questions regarding how to implement such thing, please do not hesitate to contact us. The [Extensibility paragraph](https://github.com/Azure/diagnostics-eventflow#extensibility) in the README should get you started.

Hope this helps!
Karol

**Comment by karolz-ms** [comment] 2018-11-27 18:38
Closing this one for now, but feel free to ask any follow-up questions!

**Closed by karolz-ms** 2018-11-27 18:38 UTC

**Comment by voltcode** [comment] 2018-11-28 16:04
I noticed that HttpOutput does not send metadata, which is essential to deserialize EventData in full so it's useful for further processing by EventFlow. Should this be considered as a bug? Perhaps a config option should be present to decide whether HttpOutput should send metadata?

**Comment by karolz-ms** [comment] 2018-11-28 17:52
No it is not a bug.

The metadata is an EventFlow concept. HttpOutput is supposed to work with any service that accepts JSON over HTTP. It is not reasonable to expect that such service will understand EventFlow metadata and do something useful with it, at least not in general case.

In fact, metadata is never supposed to be *sent*. It is *a hint how the data (payload) **could** be interpreted*. None of the EventFlow outputs (at least these owned by Microsoft) send any metadata anywhere. They all just make changes to, or produce new data, based on metadata. If you want to send something, just put it in the payload.

If you need your own metadata processing logic, implement it in a custom filter that sits in front of an output (e.g. HttpOutput).
